services:
  frontend:
    build: .
    container_name: ent_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./login:/usr/share/nginx/html/login:ro
      - ./admin:/usr/share/nginx/html/admin:ro
      - ./etudiant:/usr/share/nginx/html/etudiant:ro
      - ./enseignant:/usr/share/nginx/html/enseignant:ro
    networks:
      - default
      - ms-auth_default
      - ms-upload_default
      - ms-download_default
      - ms-admin_default
      - ms-calendar_default
      - ms-notes_default
      - ent_rabbitmq_net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default:
    name: frontend_default

  ms-auth_default:
    external: true

  ms-upload_default:
    external: true

  ms-download_default:
    external: true

  ms-admin_default:
    external: true

  ms-calendar_default:
    external: true

  ms-notes_default:
    external: true

  ent_rabbitmq_net:
    external: true
