CREATE DATABASE IF NOT EXISTS ent_messaging;
CREATE DATABASE IF NOT EXISTS ent_admin;
CREATE DATABASE IF NOT EXISTS ent_upload;
CREATE DATABASE IF NOT EXISTS ent_calendar;
CREATE DATABASE IF NOT EXISTS ent_notes;