apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "ent.namespace" . }}
  labels:
    {{- include "ent.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
  annotations:
    description: "Espace Numérique de Travail — EST Salé"
    contact: "jto@est-sale.ma"
